### ISSUE TITLE
Flaky: KeycloakLoginTestWithCaching#testLoginCacheSize

### ISSUE THREAD

**Issue by kthoms** [operaton/operaton-keycloak#14]
**Describe the bug**
`org.operaton.bpm.extension.keycloak.test.KeycloakLoginTestWithCaching#testLoginCacheSize` fails:

```
junit.framework.AssertionFailedError: expected:<[operaton@accso.de, johnfoo@gmail.com]> but was:<[johnfoo@gmail.com, operaton@accso.de]>
Expected :[operaton@accso.de, johnfoo@gmail.com]
Actual   :[johnfoo@gmail.com, operaton@accso.de]
<Click to see difference>


	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:86)
	at junit.framework.TestCase.assertEquals(TestCase.java:246)
	at org.operaton.bpm.extension.keycloak.test.KeycloakLoginTestWithCaching.testLoginCacheSize(KeycloakLoginTestWithCaching.java:165)
```

**To Reproduce**
Executed all tests in IJ.

**Expected behavior**
Test should pass.

**Comment by kthoms** [comment]
`getCacheEntries` returns a sorted list, but the test expectation is not in alphabetical order. This is a bug in the test expectation.

**Comment by kthoms** [comment]
Same holds for `org.operaton.bpm.extension.keycloak.test.KeycloakGroupQueryTestWithCachingAndMaxSize#testCacheEntriesEvictedWhenMaxSizeIsReached`
